import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ background: "lightblue", marginBottom: "1rem" }}>
          <a href="/">Home</a>
        </nav>
        {children}
        <footer style={{ background: "lightblue", position: "fixed", bottom: 0, width: "100%"}}>© 2024 My Blog</footer>
      </body>
    </html>
  );
}
